name: logger
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 2.5.0
repository: https://github.com/SourceHorizon/logger

topics:
- cli
- logging

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  test: ^1.16.8
  lints: ^2.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
